version: '2'
services:
  eureka:
    image: com.hstreb/eureka-server
    ports:
      - "8761:8761"
  product-web:
    image: com.hstreb/product-web
    ports:
      - "8383:8383"
    environment:
    - EUREKA_PORT=8761
    - EUREKA_URL=eureka
  product-catalog:
    image: com.hstreb/product-catalog
    ports:
      - "8181:8181"
    environment:
    - EUREKA_PORT=8761
    - EUREKA_URL=eureka